replicaCount: 1

image:
  repository: theiaide/theia
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configMap:
  enabled: true
  name: script
  data: 
    listar.sh: |-
      #!/bin/bash
      ls -ltra
      echo "acabei de listar"


serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 1001
#  fsGroup: 1001


service:
  type: ClusterIP
  port: 80

ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
        - host: chart-example.local
          paths:
              - path: /
                pathType: ImplementationSpecific
    tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http


volumes:
- name: theia-volume
  configMap:
    defaultMode: 0777
    name: theia-volume
    optional: false

volumeMounts:
- mountPath: /home/project
  name: theia-volume
