{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "theia-fernando.fullname" . }}
  namespace: {{ .Values.configMap.namespace }}
# Pedir para voltar nesse ponto do loop 
data: 
    listar.sh: |-
     #!/bin/bash
     ls -ltra
     echo "acabei de listar"

{{- end -}}