{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "theia-fernando.fullname" . }}
{{- with .Values.configMap.data }}
data:
  {{ toYaml . | nindent 2 }}
{{- end -}}

{{- end }}