replicaCount: 1

image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
    create: true
    annotations: {}
    name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
    type: ClusterIP
    port: 80

ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
        - host: meuapp.com.br
          paths:
              - "/"
    tls: []

resources: {}

autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
    httpGet:
        path: /
        port: http
readinessProbe:
    httpGet:
        path: /
        port: http
